* 2018
** March
*** 06
Trying to get clojurescript/reframe/electron app to build with support for re-frame-10x. Re-organised and cleaned up the project.clj file (hinh-anh, master branch commit 9b07d58a1a02be7df9ab0a6b1aa287b6c867b712)

Current problem is that electron is now looking for the html file in the wrong place. I have told clojurescript to use tmp as the folder to store any of the build files but now electron is looking in there for the html too. Reverted to building in app/dev ans app/prod.

Now having trouble getting lein clean to trigger a recompile. Doing:
#+BEGIN_SRC shell
lein clean
lein descjop-once-dev
#+END_SRC
doesn't cause a recompile unless the source has changed aswell.
*** 07
Trying to build a re-frame/electron project avoiding the problem apparant in hinh-anh commit 2517e439239f1a0a9423707033a8494953ce01bd where figwheel auto refresh doesn't work. Step at a time this time, checking all the way.

New empty descjop project, refresh ok

Cleaned up project.clj, added alias for rebuild, refresh ok

Added re-frame dependancies
Added files for front/re-frame config.cljs events.cljs subs.cljs views.cljs
Edit front/core.cljs
Edit dev/main.js Uncomment the section for no optimization and change the paths to point to out_main.
edit src/project/core.cljs. Uncomment the section for no optimisation. refresh ok.

Looks like I had clobbered the main.js file in hinh-anh. This is not generated by the build and should be under source code control.
*** 08
**** First attempt at getting electron and descjop working together
Turns out the test project fails when rebuilt. Seems to be wrapped up in switching to no optimisations. Start again with a descjop project and get that working. The changes have been applied to hinh-anh commit 81231522bf125e83be556b8ac4f204224230f68b This fails on lein rebuild with an error like this:
#+BEGIN_SRC shell
(master) working: lein nuke
(master) working: lein rebuild
Compiling ClojureScript...
Compiling "app/dev/js/cljsbuild-main.js" from ["src"]...
Compiling "app/dev/js/cljsbuild-main.js" failed.
Exception in thread "main" java.lang.AssertionError: Assert failed: :nodejs target with :none optimizations requires a :main entry
(not (and (= target :nodejs) (= optimizations :none) (not (contains? opts :main)))), compiling:(/private/var/folders/8z/fnlgpwg91ml91_fsljwj9x0h0000gn/T/form-init3496121715080043611.clj:1:125)
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
8<-----
#+END_SRC
Tried full clean of the test project and it does the same. Adding :main "blank.core" to the dev-main build fixes this but then electron throws an error on refresh:
#+BEGIN_SRC shell
blank: ./electron/Electron.app/Contents/MacOS/Electron app/dev
Start descjop application on Darwin.
Error: async hook stack has become corrupted (actual: 5, expected: 0)
 1: node::AsyncWrap::PopAsyncIds(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/iain/Code/Clojure/Descjop/blank/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/Users/iain/Code/Clojure/Descjop/blank/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: void node::BaseObject::WeakCallback<node::PromiseWrap>(v8::WeakCallbackInfo<node::PromiseWrap> const&) [/Users/iain/Code/Clojure/Descjop/blank/electron/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
8<--------
#+END_SRC
Back to the begining and try to get a basic descjop project to work with no optimisations. This time the test project goes under git. First, a little sidetrack:

**** Electron Template
[[https://github.com/ducky427/electron-template][electron-template]] is an alternative to descjop that uses only a single build and specifies a :main. :main appears to point to a cljs namespace that just has a call to the main init function.

**** Successfull attempt at electron/descjop/re-frame project
Looking good, the dev-front build is where the :main and :optimisations none should go. Also needs :asset-path setting to dev/out_front. With this in place, the calls to goog etc can be removed from index.html and all works well, so back to installing re-frame-10x. Looks good until the cljs repl starts up and gives this error:
#+BEGIN_SRC clojure
user> Figwheel: Starting server at http://0.0.0.0:3449
Figwheel: Watching build - dev-front
Figwheel: Cleaning build - dev-front
Compiling "app/dev/js/front.js" from ["src_front" "src_front_profile/setup_front/dev"]...
Failed to compile "app/dev/js/front.js" in 6.294 seconds.
----  Could not Analyze  app/dev/js/out_front/mranderson047/reagent/v0v8v0_alpha2/reagent/impl/component.cljs  ----

  No such namespace: create-react-class, could not locate create_react_class.cljs, create_react_class.cljc, or Closure namespace "create-react-class"

----  Analysis Error : Please see app/dev/js/out_front/mranderson047/reagent/v0v8v0_alpha2/reagent/impl/component.cljs  ----
Launching ClojureScript REPL for build: dev-front
Figwheel Controls:
          (stop-autobuild)                ;; stops Figwheel autobuilder
          (start-autobuild [id ...])      ;; starts autobuilder focused on optional ids
          (switch-to-build id ...)        ;; switches autobuilder to different build
          (reset-autobuild)               ;; stops, cleans, and starts autobuilder
          (reload-config)                 ;; reloads build config and resets autobuild
          (build-once [id ...])           ;; builds source one time
          (clean-builds [id ..])          ;; deletes compiled cljs target files
          (print-config [id ...])         ;; prints out build configurations
          (fig-status)                    ;; displays current state of system
          (figwheel.client/set-autoload false)    ;; will turn autoloading off
          (figwheel.client/set-repl-pprint false) ;; will turn pretty printing off
  Switch REPL build focus:
          :cljs/quit                      ;; allows you to switch REPL to another build
    Docs: (doc function-name-here)
    Exit: Control+C or :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
Prompt will show when Figwheel connects to your application

#+END_SRC
Duh, forgot to include re-frame. Fixed that, now I get:
#+BEGIN_SRC clojure
user> Figwheel: Starting server at http://0.0.0.0:3449
Figwheel: Watching build - dev-front
Compiling "app/dev/js/front.js" from ["src_front" "src_front_profile/setup_front/dev"]...
Failed to compile "app/dev/js/front.js" in 2.544 seconds.
----  Could not Analyze  app/dev/js/out_front/day8/re_frame_10x/subs.cljs  ----

  No such namespace: cljs.spec.alpha, could not locate cljs/spec/alpha.cljs, cljs/spec/alpha.cljc, or Closure namespace "cljs.spec.alpha"

----  Analysis Error : Please see app/dev/js/out_front/day8/re_frame_10x/subs.cljs  ----
Launching ClojureScript REPL for build: dev-front

#+END_SRC
This is part of clojurescript. Updating to the latest version fixed it
** April
*** 18
Trouble with cljs repl. Trying revert cider to a release version rather than 17-SNAPSHOT
package-delete cider, had to remove ac-cider and clj-refactor first
** June
*** 25
Trouble with mongo. New version from macports didn't like the old db. Needed to update the featureCompatibilityVersion to 3.4 to make it readable by the 3.6 binary.
#+BEGIN_SRC
db.adminCommand( { getParameter: 1, featureCompatibilityVersion: 1 } )
db.adminCommand( { setFeatureCompatibilityVersion: "3.4" } )
#+END_SRC
To do this meant using an earlier version of mongod, which is no longer available from macports, but is still there on the mongo site. Installed in ~/bin/mongodb-3.4 just incase it's needed again. Comment and uncomment in ~/bin/mongo-start as necessary. The backups of ~/db are still at 3.2 I think so it might be useful.

at some point I should probably run this:
#+BEGIN_SRC
db.adminCommand( { setFeatureCompatibilityVersion: "3.6" } )
#+END_SRC
I will wait though. The mongo site warns that 3.6 is untested with apfs under mac osx 10.13. Seems to work ok so far.
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/
Might be an idea to switch to ~launchd~ but shell script from system-prefs:users:startup-items is working fine:
https://stackoverflow.com/questions/5596521/what-is-the-correct-way-to-start-a-mongod-service-on-linux-os-x
** July
*** 06
Building photo-api, problems with cider. It's required in core.clj but no longer in the project file. Removing it and the (mount/defstate ....) fn that calls makes the lein uberjar command work ok, but then the dev version wont run, so they have to get put back in. This can probably be avoided by updating the Luminus stuff it was built on.
*** 21
Playing with mpd and other alternative music players. Most of the pain involved was due to launchd (fuck you apple) and macports. Ended up installing mpd using brew instead.

**** mpc
useable, from the command line.

**** ncmpcpp
Pretty good once I set up the keybindings. Will need an alias, no way I can remember that bloody name.

**** Emacs
***** Mingus
Pretty good

***** Bongo
Doesn't use mpd by default, but I think it can. Really like the way it just uses a playlist that is pretty much just a text file. Delete a line to remove it etc. Also links directly to the file system. Hit d to see a dired buffer of the track at point. Might not be so good for browsing.

***** simple-mpc
workeable, simple.

***** Junk
****** libmpdee
Complex. Investigate further sometime. Needs hand installing.

****** ampc
Fiddly, confusing, ugly.
** September
*** 20
Experimenting with web bookmarks from Emacs
http://www.soulflyer.com
http://www.soulflyer.co.uk/customerphotos
opening single url's is easy, just put the cursor on the above line and run M-x browse-url. Not sure how I can do the equivalent of open all in tabs. Trying org-board, see if that can help. Nope.
Selecting a region and doing M-| xargs open will open all the urls in tabs.
