* Notes for assistants
** Briefing
*** Don't forget to look at the camera
Many new divers don't look around at all. They only see a very narow tunnel directly in front of them.

*** Don't follow the cameraman
Just keep going, I will position myself ready for the next shot based on where you are going.

*** Don't hold the reg
Makes the diver look tense.

*** Relax the arms
Doesn't look cool. Experienced divers rarely use their hands.

*** Respect for the environment. No touching.

** Signals
Mostly just need the usual, up, down, this way, problem and ok signals, but add this one:
*** Strobes
I sometimes have problems with the strobes. Usually this is one of them failing to fire. Normally I will spot this and sort it out myself, but if you see it, please let me know.
** Shots
I usually try to get a number of different shots, each of which needs a different setup.
*** Surface
Surface shots often come out really well and aren't dependant on good water conditions. If the vis is bad, it's especially important to get a few good surface shots. All surface shots need the port clearing. This takes a small amount of time, carefully pouring the water off the port so it doesn't form droplets. Unfortunately this can't be pre prepared, the camera has to be in the water for most of the time. If it's held out of the water for very long then there is a serious risk of condensation forming on the inside of the port. This clears after a few minutes in the water but means that the camera can't be used until it clears. This is especially a problem on sunny days, when it is best not to lift the camera out of the water for more than a few seconds.
**** Entry
I usually try to get a sequence of shots as the diver enters the water. This requires careful timing as the camera (G15) will only shoot continuously for 1 second. A count-in by the DM helps, but if the diver doesn't step on 3 it takes a few seconds for the camera to complete writting the sequence before I can try for a second set of shots.

**** Surface portraits
It's good to get a few, some with the boat in the background, some with the shore or open sea. These are the easiest shots to get and often the most striking. They do take preparation time though, clearing the port. I prefer to get these before descent. Often there is no chance after surfacing, especially if the diver surfaces near to the ladder.

*** Underwater
Switching the camera from surface to underwater takes time. Settings need to be changed and the strobes need to be turned on, positioned and tested, all while keeping up with the diver and guide. No point posing for pics until this is done. The strobes flashing show that I'm ready to go.

**** OK pose
I don't like these much, but the customers do. Easy to take, just stop and face the camera while the diver does the ok sign or v-sign or whatever. Best taken facing towards the sun. It does make a difference to the quality of the shots, even if it doesn't seem to be obvious at the time.

**** Side action shot
Diver swimming along in reasonable trim, with coral in the background. Hardest part of getting this shot is getting the diver to look at the camera without stopping and posing. I will swim alongside and just watch for the diver turning to face me.

**** Head on action shot
My favorite. I will swim ahead and position myself somewhere where I can catch the diver facing me. Usually this will be next to a big coral covered rock. If possible, keep the diver low, ideally below the top of the rock. Stay fairly close to the rock, as long as they aren't flailing arms around. Often there is a best direction for these shots, so I may take them on the way out, or the way back. This mostly depends on the sun.

**** Head on pose
A variation of the head on action shot. Just stop next to the rock. It's a bit more difficult, and doesn't look as good. Still good to get, especially if the diver isn't inclined to look at the camera while swimming.

**** Fish foreground
It's often easy to put a shoal of fish between the camera and the diver. Not so easy to get the diver to look towards the camera at the right moment. The moment is usually very brief. Either the fish get spooked and swim off or the diver keeps on moving and rapidly ends up out of shot.

**** Annoying nemo
Some fish will actively threaten a diver that comes too close to their territory, so its possible to get a shot where fish and diver are close together and both in focus. Positioning is tricky as the camera has to be alongside, looking sideways, not above looking down. Don't stay too long though, best not to stress the fish out.

**** Halo
Very tricky to get just right. I usually go for this on the last part of a dive when the diver is not so close to the coral. I will be facing up, below the diver. Just keep moving slowly. I will take the shot when the diver lines up with the sun.

**** Ascent
In vertical posture on the way to the surface. This can look really good, especially if the ladder is in the background. Hardest part here is getting the diver to face the camera.

**** Exit
Not currently taking these, as there isn't room under the back of the Alpha boat to do it safely.
