* current agreement

10% for staff before split. (the 5% for the translator was not deducted last payday)
remainder split 70% 30%

so for each $100:

|-------+-----|
| crew  | $10 |
| alpha | $27 |
| iain  | $63 |
|-------+-----|

* todays suggestion

alpha $40
crew/iain  split $60, proportion yet to be agreed.


Although this looks like a small shift, it's not. The split has so far been made AFTER deduction of the crew's share. This changes that so Alpha takes their percentage first. This makes an enormous difference to the relative incomes.
|-------+------+------|
| crew  | $30? | +20? |
| alpha | $40  | +13  |
| iain  | $30  | -33? |
|-------+------+------|


* Counter suggestion

|-------+--------+---------------|
|       |        | relative rate |
|-------+--------+---------------|
| crew  | $25.00 |           +15 |
| alpha | $25.00 |         -2.00 |
| iain  | $50.00 |        -13.00 |
|-------+--------+---------------|

The crew may deserve a bigger cut, but bear in mind that the work on the boat is actually less than half of what goes in to producing high quality pictures. If I have to complete one days pictures within a day, it will generally take me until midnight. Also I need to cover costs, photo gear is expensive and vulnerable. At the moment I make barely enough to cover my running/repair/depreciation costs with little or no actual income. This is ok for now, working on the assumption that there are better things in the future.

Giving the crew only 60% of the cut is not justification for reducing my cut for 2 reasons:

1) You are already paying them for their time.
2) Divemaster with a camera is not the same as photographer. If you want the extra quality to improve the company reputation and benefit Alpha in the long run then you need to pay a little extra. It's not much.

* try again

If you want to renegotiate our agreement, then ok we can talk. First though, I need to make some thing clear. They are your crew. I have no authority there, no say in hiring or firing, or delegation of duties, or anything. Without the authority I can't be expected to take the responsibilty, Alpha is solely responsible for them. This means my cut, whatever it is we agree on, is not in any way affected by whatever has to be done to keep the crew happy.

Realistically, the extra work the crew do to make the photos go smoothly is small. A slight re-arrangement of running order, maybe a short wait on the surface, and a few extra words in the briefing. The 10% or 15% was an entirely reasonable amount to cover that, and I was more than happy to share providing that with Alpha. Sadly that is not the problem now, what we are looking at here is a backhander to keep them sweet rather than payment for effort. Because they are allowed to take photos (while on salary!) they are going to want a fairly large backhander to compensate for that loss of earnings. This is not something that is in any way my responsibility, and I can't take on sharing that.

Your suggestion that Alpha take 40% and then I get to argue with the crew over the rest is not acceptable. I would consider a 50/50 split, but that is not enough on its own. I would also need your crew to be ok about it. I suspect you would need to give them a large part of your share to make that happen.

I am, however, quite happy to share days, share skills, and share photos. It looks like some of the crew are making serious efforts to improve their photography and I am all for encouraging that.

Having quality photos is perhaps a luxury Alpha can't afford at the moment? Divemasters with cameras can make the same money. As long as this is purely a short term money generating exercise, then I have nothing extra to offer. You don't need me for that.

Before you make any decision I would like you to run a simple comparison of photos. When I take photos I have certain standards that each picture needs to meet. Some are absolute, ie if it's out of focus or badly burnt out it gets deleted. After that it needs to have as many as possible of a list of requirements:

Face, including eyes, is visible
Skin is reasonable colour. People are not blue.
Interesting background, coral, rock or waves
Interaction (not interference) with wildlife
Good composition

Anything that doesn't get at least one of these right is immediately out. Normally I'm looking for 3 or more ticks before the customer will get the pic, unless the conditions are really difficult when I might allow a 1 or a 2 through. The very best of the divemaster photos I have seen so far might just scrape through these standards. Most don't even come close. Achieving this takes a lot of things, long experience, the right equipment, and most of all, lots of work. The result is pictures that are likely to get shared and noticed. Divemaster standard pics may satisfy the customer initially but are unlikely to reflect well on the divecentre, if they even get shared at all.

If you do want high quality photos then let me know. Meanwhile I am happy taking a break and working on other stuff to improve my picture processing and delivery system.
