* Basics

Start with the first task. To move on to the next task you need to get full marks. You can try each task as many times as you like.

** Task 1
------
Just send me a picture. Put your camera on manual mode and take a correctly exposed picture. If your camera allows it, set it to display the histogram on the lcd for both live view and replay modes. A correctly exposed picture should have a good spread across the histogram.

Tell me what settings were used (ISO, shutterspeed and aperture) This information will be encoded in the picture by the camera. You must check that it is there and make sure it matches, because some software removes this information.

To get full marks the details contained in the exif data in the picture you send me should match the details in your reply message. Picture quality does not count toward the mark for this first task, but remember the rule: "Don't let anyone see the rubbish" This is an important rule. Everyone takes bad photos sometimes. Only show the best ones.

To successfully complete this, you will need to learn how to read exif data in-camera and in a picture viewer of your choosing.

Here is an example. It was taken using these settings:
ISO: 100
Shutter: 1/60
Aperture: f8
If you open up the picture you can check these settings.
To do this you will need to find a photoviewer that allows you to see this information.

** Task 2
Take 2 photos of the same subject. The first using your favorite automatic or semi-automatic mode. The second must be on manual mode. It should look as close as possible to the first picture.

** Task 3
Take a series of photos, minimum 10, with the camera on manual. All should be correctly exposed, ie not too bright or not too dark, and no burn out in the white parts.

** Aperture v Shutter speed
Set your camera on manual and choose an ISO setting. 100 would be a good choice outside, but use something higher if you are inside. Using the same ISO setting take 2 photos with different aperture sizes. Both photos must be correctly exposed and as far as possible look the same.

** Shutter speed
Take a picture of a moving subject. Passing traffic is ideal. take 2 shots, one using a slow shutter speed (1/60 or slower) and one using a faster shutter speed (1/250 or faster) Adjust aperture and ISO as necessary to get the exposures aproximately the same. What are the advantages and disadvantages of the different shutter speeds.

** Aperture
Take a portrait of someone. The shot should be taken against a background that is at least 2m behind the subject. Take the shot twice using your minimum and your maximum aperture sizes. Adjust shutter speed and ISO as necessary to get the exposure to be the approximately the same, but bear in mind that the shutter speed shouldn't be too slow or you will get motion blur. Are there any noticeable differences in the 2 photos? Are there any advantages or disadvantages to using these diiferent aperture sizes?

** ISO
Take a series of pictures at sundown (or sunrise if you wish) of the same view. Try and keep the exposure the same for the whole sequence. The first (or last) shot should be in full daylight and the last (or first) should be in almost complete darkness. You can change any settings you wish to acheive this. I would suggest keeping the shutter speed set to the slowest speed you can use without getting blur from camera shake. This is normally about 1/60 for a 60mm lens (adjust for a different lens focal length). It can be even slower if you have image stabilisation. You will need to open up the aperture and increase the ISO as the light fails. You already know the advantages and disadvantages of different aperture sizes (and shutter speeds), so what advantages and disadvantages can you see that are introduced by changing the ISO?

* Composition
walk out your door and find examples of these shapes
Collect the alphabet
