#+TITLE: uillean pipe voicing
# TAGS

http://uilleannforum.com/forums/viewtopic.php?f=4&t=767

 Post by billh » Wed Sep 19, 2007 7:20 pm
Hi Quint:

This is an excellent important topic. However it's one where you're likely to find big differences of opinion. I also suspect that even among experienced folks whose approach to voicing is broadly similar, many may find it hard to explain exactly what they are doing, or put they "system" into words. Since the tuning and timbre of a pipe chanter is an interconnected system, it can be pretty hard to boil it down to a simple recipe (and possibly misleading).

Personally I seem to be getting good results when voicing chanters, but certainly I don't feel that I have enough experience or understanding to claim to be an authority, or to distill the more subtle points into a definitive "system". From time to time I have heard (or read) someone's exposition of such a system, but I have yet to read one which I believe :-)

As you infer, this is one of the "black art" areas of pipemaking, and possibly some of those people who have a good understanding of it are choosing to remain silent on the subject. To be fair, it may well be that, while they may have developed an "intuition" for it, a systematic understanding of it eludes even the experienced. I suspect a little of both are at work - one learns by experience what works for a particular set of chanter designs, but the specifics don't always generalize well; I think this is particularly true of the details of "which direction to undercut" in various circumstances. I have heard it said that undercutting "downwards" selectively raises the second octave, i.e. broadens the octave, whereas undercutting upwards has more of an effect on the first octave, but my own experiences have not really borne this out consistently. As you probably know, even something as basic as enlarging a tonehole can have different effects depending on which tonehole (for instance, enlarging the F# can flatten the note instead of sharpen it; if you plotted "pitch vs tonehole size" for F# I think the graph would have a dip in the middle and then rise at both extremes).

OK, back to the topic - a couple of points are worth mentioning I think. Forgive me if they seem obvious - but voicing and tuning are necessarily interrelated, insofar as most adjustments which affect tuning will also effect response, timbre, volume, etc. - i.e the "voice" of the chanter. Likewise the "voicing" operation, which the name implies mostly affects the timbre and response of the chanter, always impacts tuning. If you are lucky, your design is good, and the stars are properly aligned, "voicing" a newly-made chanter will greatly improve its tuning.

With those disclaimers, I'll try to describe a bit of what I currently do.

When I think of, or say, "voicing", I think of the operations that I do after boring the chanter and drilling the toneholes to their initial sizes. I also think of voicing as the operations which would be desirable/beneficial to the performace of the chanter even in the absence of tuning issues. If the chanter design is one I know and trust, the "initial" sizes which I drill are pretty much the measured minimum sizes as measured from the "model". If the design is suspect, I may drill a couple of toneholes undersized, but this is risky since one can easily end up with a working, but quite different, chanter this way, via changes in reed insertion depth, reed adjustment, etc. Some people may include selective re-reaming of the chanter in the "voicing" operations, for instance reaming the chanter until octaves come into tune with a particular reed (after tonehole adjustments, below), or reaming the bell to bring in the bottom D, etc. I do a little but of this but mostly I try to get the bore pretty much to target before starting to voice/tune.

The first thing I do, and maybe the most important in my opinion, is to round/chamfer all toneholes quite noticeably inside and out. On the inside, this isn't "undercutting" in the sense that the goal is to make the tonehole act a lot larger, or alter tuning, but primarily its goal is to reduce turbulence at the tonehole edges. It does have the side-effect of making the holes act as though they were a bit larger in some respects, for instance if there are notes that were balky or airy toned in the "as drilled" state, this will often improve them dramatically. (Look for an immediate effect on the C#, Es, and ghost D).

About the same time, or just before, I take care of any anticipated scalloping - on some designs this may be very subtle, less than 1mm, or non-existant; on others, for instance the back d on most concert pitch designs, the scalloping can be quite strong. If I adjust the scalloping I always round/chamfer the tonehole exit again.

If the back d and bottom D are mostly behaving, and on pitch, I tend to look at the C's. If the C# is a tad flat, and the two-finger forked C natural a bit stuffy, then I start undercutting the C and the F#. If the F# is already flat, this may be dangerous, but if it's a little bit sharp in the first octave and a little flat in the second, undercutting should solve all problems more or less at once. Well, one can always hope! At the moment my belief is that undercutting the F# (which way? either?) eases and flattens the C natural, whereas undercutting the C# tonehole raises the C# and C natural - possibly working against the F# undercut a bit. So when doing this operation I tend to "see saw" back and forth, paying close attention to whether things are converging.

While I have definite working theories from that point on, I don't feel confident to generalize them; suffice it to say, for now, that I proceed to undercutting individual toneholes in response to tuning issues that cannot be readily fixed with the reed. I tend to try the "undercut down to widen the octave, up to narrow/keep it" theory, but in reality anything which makes a tonehole less resistant will tend to sharpen the second octave. From a theoretical perspective the "tonehole correction" is longer in the second octave, which means that for instance if the G hole is quite small relative to the rest of the toneholes, your second octave G is going to tend to be flat. Also, while we're talking theory, all undercutting widens the bore, so undercutting will tend to sharpen all notes below it a tiny bit. A good reason for going slowly, in iterations!

There is another school of thought that regards chimney height adjustments or even rounding of toneholes as unnecessary or undesirable, and undercutting as something to be avoided if possible; if I understand this point of view correctly, all necessary adjustments to the toneholes should be strictly via diameters and placement. I am not sure what meaning the term "voicing" might have in this methodology - one of the practicioners will have to help you out there.

Best regards,

Bill