#+TITLE: hide org-links buffer
# Tags #emacs #org-mode #webbookmark
https://www.mail-archive.com/emacs-orgmode@gnu.org/msg136936.html

Re: How to hide *Org Links* buffer when insert new links?
Ihor Radchenko Mon, 31 May 2021 05:51:26 -0700

Shiyao MA <i...@introo.me> writes:

> Hi,
>
> When insert org links with org-insert-link, an Org Links buffer is created.
>
> How can I hide it?

You cannot prevent it from being created. It is hard-coded. However, you
should be able to prevent Emacs from showing the buffer window by
modifying your display-buffer-alist:

(add-to-list 'display-buffer-alist '(("Org Links" display-buffer-no-window
(allow-no-window . t))))

... except you cannot. Apparently, Org mode is being too aggressive and
ignores display-buffer-alist. I do not think that it is supposed to
happen. The patch fixing current aggressive behaviour and allowing the
above code to work is attached.

Dear All,

I do not think that unconditionally setting display-buffer-alist to nil
in org-no-popups macro is the right thing to do. I updated the macro
using pop-up-windows setting to nil instead of completely trashing
user-defined display-buffer-alist. The latter is nil by default and if
not, the user should know what he/she is doing.

Best,
Ihor

>From c598f0208738f16b6d00c05a7338c226d15f5d12 Mon Sep 17 00:00:00 2001
Message-Id: <c598f0208738f16b6d00c05a7338c226d15f5d12.1622465359.git.yanta...@gmail.com>
From: Ihor Radchenko <yanta...@gmail.com>
Date: Mon, 31 May 2021 20:47:45 +0800
Subject: [PATCH] Do not ignore user-defined display-buffer-alist in
 org-insert-link

* lisp/ol.el (org-insert-link): Handle case when *Org Links* window is
not created.
* lisp/org-macs.el (org-no-popups): Do not override
`display-buffer-alist'. Use `pop-up-windows' instead.
---
 lisp/ol.el       | 13 +++++++------
 lisp/org-macs.el |  2 +-
 2 files changed, 8 insertions(+), 7 deletions(-)

diff --git a/lisp/ol.el b/lisp/ol.el
index a2cf872b8..ae0177695 100644
--- a/lisp/ol.el
+++ b/lisp/ol.el
@@ -1856,12 +1856,13 @@ (defun org-insert-link (&optional complete-file link-location description)
 			     (reverse org-stored-links)
 			     "\n")))
 	(goto-char (point-min)))
-      (let ((cw (selected-window)))
-	(select-window (get-buffer-window "*Org Links*" 'visible))
-	(with-current-buffer "*Org Links*" (setq truncate-lines t))
-	(unless (pos-visible-in-window-p (point-max))
-	  (org-fit-window-to-buffer))
-	(and (window-live-p cw) (select-window cw)))
+      (when (get-buffer-window "*Org Links*" 'visible)
+        (let ((cw (selected-window)))
+	  (select-window (get-buffer-window "*Org Links*" 'visible))
+	  (with-current-buffer "*Org Links*" (setq truncate-lines t))
+	  (unless (pos-visible-in-window-p (point-max))
+	    (org-fit-window-to-buffer))
+	  (and (window-live-p cw) (select-window cw))))
       (setq all-prefixes (append (mapcar #'car abbrevs)
 				 (mapcar #'car org-link-abbrev-alist)
 				 (org-link-types)))
diff --git a/lisp/org-macs.el b/lisp/org-macs.el
index d56fc3bce..133960fea 100644
--- a/lisp/org-macs.el
+++ b/lisp/org-macs.el
@@ -170,7 +170,7 @@ (defmacro org-preserve-local-variables (&rest body)

 (defmacro org-no-popups (&rest body)
   "Suppress popup windows and evaluate BODY."
-  `(let (pop-up-frames display-buffer-alist)
+  `(let (pop-up-frames pop-up-windows)
      ,@body))

 
--
2.26.3
