#+TITLE: ai blog post
# Tags #ai

* The AI bubble

It seems that the number of people that think AI is a great idea is larger than the number of people that actually understand what it is and what it can do. Discussions on the topic still contain a lot of conjecture, prediction, and expectation alongside the current reality.

Looking closely at the actual output rather than the hype, a lot of the good stuff seems to fall under the heading of "sophisticated autocomplete" or "lorem ipsum on steroids".

Meanwhile the negative aspects of AI are easier to identify. Any web search now turns up a vast number of results that are clearly generated by AI, or aggregated from other similar pages which were also possibly generated by AI. Finding useful and reliable results is now much harder. A few years ago there was a good chance that a well thought out search query would return your answer as the first hit. Remember the "I feel lucky" button? Now it is unlikely that the good stuff will even be on the first page of results. This is really only an irritation, but one that comes at a significant cost, particularly in areas (like software development) where web searches are a part of the routine workflow. 
This stuff isn't going away. It's a "forever chemical" introduced into the waters of the internet.  Mitigating the damage done will be a growing market for those that do actually understand the technology.

Generation of images is a bit more of a serious problem. Sure, the marketing department can get anything they want without having to pay for a stock shot. But alongside this is the destruction of all credibility of images, and increasingly video too. It used to be said that "A photo never lies". This wasn't exactly true, and it has always been possible for a good photographer to creatively mislead. However it was still possible to extract some information from a photo. Editing has always been detectable. Taking a look at the pixel level reveals artifacts that betray the use of an editor. AI is increasingly being used to "improve" this. Sure it's easy to spot extra fingers and such, but will we still be able to detect the fake when that kind of high level mistake is corrected?

, and "Untainted by AI" will be a valuable badge.
