#+TITLE: applications
# Tags #osx

I know I had something to do x but can't remember what it was called....
Open apps using *open-app* with the point over the app name or the appname selected in the region.
* Beat Slicing
ReCycle, old mac only. Looks like it is also available for apple silicon. Just need to enter the licence...

* Bootable USB
Etcher or BalenaEtcher for making bootable USB drives
* Disk usage
Grandperspective

* Mobi, epub Reader
Okular seems to be the least crap.
* Editing Audio
Audacity
Call from dired in emacs with *open -a audacity*

* Flac splitter
XLD
** Command line use:
*** Instructions
HOW TO USE

1. Copy XLD.app to the place you like (e.g. /Applications)
2. Edit XLD_APP variable in "xld" shell script included in this folder
   (If you have copied XLD.app to /Applications, you don't have to edit)
3. Now "xld" shell script works as a command-line XLD
*** Script
#+begin_src shell
#!/bin/sh
#Edit this line to define a path to XLD.app
XLD_APP="/Applications/XLD.app"

if [ ! -d "${XLD_APP}" ] ; then
	echo "XLD.app not found"
	exit;
fi

"${XLD_APP}/Contents/MacOS/XLD" --cmdline "$@"
#+end_src
** Readme:
X Lossless Decoder (GUI)

X Lossless Decoder (XLD) is a decoder which supports various lossless audio format. It runs on Mac OS X 10.4 and later.

How to use

Decode file
Drag & drop the file you want to decode on the icon of XLD, or open the file from a dialog by choosing 'File' -> 'Open' . Soon XLD begins decoding if the opened file is supported by XLD.
Output format and destination can be selected from the preference pane.

Split file with cue sheet
Open the cue sheet as described above. Then XLD automatically open the file to be split if it is associated with the cue sheet. Otherwise, you have to choose the file to be split through the file open dialog. You will see a track list window, and you can select tracks to be extracted by checkboxes. Multiple check/uncheck operation can be done by the contextual menu. Finally press "Extract" button to begin processing.

Play file
To play a file, please select "Show Player" from Window menu and drag file into the window appeared. If you want to play tracks in a cue sheet, open the cue sheet and double-click the track you want to play in the track window.

E-mail: xld@tmkk.undo.jp

* Fourier Analysis
Voxengo *SPAN* plugin

* LDP8 programming
freepad
* Mailer
Thunderbird

* Midi Routing
Element does midi and audio routing (untried)

* Musical notation
Musescore

* Music Player
persephone, mac mpd client
* Notifications
To remove lots of notifications (Typically Disk not ejected properly) kill the *Notification Center* It will restart automatically
* Sample player
sforzando (untried)
* Screen Saver
Artsaver. To get to it in the setings, scroll down to *other* and then cursor right to the end

* Synth
Vintage
* Window manager
Mostly handled by *Yabai* with *Swiftbar* to keep an eye on spaces and *on-top* settings

* Wine
whisky is a version of wine that will run on arm processors, even including 32 bit apps.
