#+TITLE: travel dates

<2007-07-08 Sun> Still in the UK, at mam's cottage
<2007-07-14 Sat> Doha passport stamp
<2007-07-15 Sun> VN Passport stamp
<2007-07-16 Mon> In Vietnam (An Phu)

<2008-05-21 Wed> In Saigon
<2008-06-02 Mon> VN passport stamp
<2008-06-04 Wed> In Uley
<2008-07-01 Tue> In Nottingham
<2008-07-14 Mon> VN Passport stamp
<2008-07-27 Sun> Back in An Phu

<2010-09-05 Sun> Penang
<2010-09-06 Mon> Malaysia passport stamp
<2010-09-07 Tue> Uley
<2010-09-28 Tue> Bute
<2010-10-14 Thu> KL, Stopover on the way home. KL Passport stamps on the 14th and 15th

<2011-05-20 Fri> Land at Heathrow
<2011-06-28 Tue> Leave Heathrow

<2012-12-07 Fri> Last dive before going to the UK
<2012-12-11 Tue> VN Passport stamp
<2012-12-13 Thu> Picked up by Steve from the airport I think.
<2013-01-12 Sat> Lift to the airport from Andy and Steph
<2013-01-13 Sun> Back in Saigon VN Passport stamp

<2014-08-18 Mon> Diving
<2014-08-19 Mon> VN Passport stamp
<2014-08-20 Wed> At Kathryn's
<2014-09-25 Thu> At the Zoo
<2014-08-28 Thu> Indistinct passport stamp. Most likely 28
<2014-10-03 Fri> Back in Nha Trang

<2017-08-02 Wed> Fly to Saigon VN Passport stamp
<2017-08-05 Sat> Kathryn's wedding
<2017-08-12 Sat> Uley
<2017-08-15 Tue> VN Passport stamp
<2017-08-18 Fri> Diving

<2019-08-05 Mon> Fly to the UK
<2019-08-23 Fri> Fly home

<2019-12-05 Thu> From Hamburg to Heathrow
<2019-12-17 Tue> Leave Heathrow

<2022-02-08 Tue> Fly to the UK
<2022-03-17 Thu> Fly Home

<2022-07-10 Sun> Pictures of Steve's mobile, think I took them just before leaving for the UK
<2022-07-28 Thu> VN passport stamp
<2022-07-31 Sun> Pictures of Kirkburton
<2022-08-13 Sat> Derwentside. Recovering from covid just in time to go home
<2022-08-17 Wed> VN Passport stamp
<2022-09-29 Thu> Back home

* Employment dates

Graduated <1996-06-30 Sun>
IMP bought by Sun <1996-03-21 Thu>
Kathryn left home december 1999
GNR sept 1998

Moved 41-43 90-91 Before R went to secondary

Married Summer 1983
Left Summer 1998 

