#+TITLE: another ai blog post
# Tags #ai #blog

* If you can't say "I don't know" you're an idiot OR People generating slop
Ai is a perfect tool to support one of the most insidiously awful human traits. This is about that trait, not directly about AI
** The need to look like we know what we are talking about
*** JS Bach
Worlds greatest composer? Even the musically ignorant know that "JS Bach" is an aceptable answer to this question.
Bit wet, with one or 2 notable exceptions. Where is the power? Music is powerful. Music can change the world. Much of this is just top quality lift (elevator) music.
*** Manchester United
Another insidiously awful human trait presents in football culture. In the UK it was never about the game, it was about belonging. Often this ended up as little more than tribal warfare between neighbouring factions. This is demonstrated by the huge police presence needed for derby matches (matches between teams based geographically close to each other). This is not an unfortunate side efect applicable only to a minority. It's where the game started, the concept of a derby match is a reference to the roots of the game where 2 villages in Derbyshire fight each other in a pretty much rule free battle.
Again, the need to sound like we know what we are talking about came into play, and due to a period of success, Man U became associated with excellence. As far as I know, this is no longer the case, but the reputation remains and allows people all over the world to talk about football and sound like they know what they are talking about.
*** Tabloids
Right wing support from the working class depends on this phenomenon. There is no advantage to anyone on low wages in voting right. 
Anyone can appear knowledgable when the tabloid papers provide neatly prepackaged opinions to share, without any need for thought and understanding. Couple this with limited exposure to unedited news and lace it with diversions and distractions and there are enough type i conservatives to keep the type Cs in power. All of this would collapse if it was socially acceptable to admit to not having a clue, and totally unacceptable to be caught faking it.
** Face saving

** Culture shift
need to move away from this (these?) destructive trait. There is strength in admitting we don't know or we were wrong.
How can we expose the weakness and avoid supporting it?
One thing that may help is identifying and labelling this trait. Labelling should be mildly insulting. "Generating slop" might be a good start, as in "Illegal immigrants are stealing out jobs? You're just generating slop..."
